spring:
  application:
    name: hello-spring-cloud-zuul
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
   sampler:
    probability: 1.0
    web:
      client:
         enabled: true
server:
  port: 16008

#zuul:
# routes:
#    hello-spring-cloud-eureka-member:
#       path:  /**
       ##service-id: http://localhost:16003/


eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver1:16000/eureka/

management:
      endpoints:
         web:
            exposure:
              include: routes

zuul:
  routes:
    hello-spring-cloud-eureka-member: /e/**
    hello-spring-cloud-fengin: /f/**


